apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: {{ .Values.objectStore.user.name }}
  namespace: {{ .Values.objectStore.namespace }}
spec:
  store: {{ .Values.objectStore.name }}
  displayName: {{ .Values.objectStore.user.displayName }}
