global:
  xraylab:
    namespace: xraylab-demo
secrets:
  xraylab:
    db:
      db_user:
      db_passwd:
      db_root_passwd:
      db_host:
      db_dbname:
      db_master_user:
      db_master_password:
